# repos:
#   - repo: https://github.com/Yelp/detect-secrets
#     rev: v1.4.0  # or latest stable version
#     hooks:
#       - id: detect-secrets
#         args: ["--baseline", ".secrets.baseline"]

repos:
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.39.0
    hooks:
      - id: ggshield-push
        language_version: python3
        stages:
          - pre-commit
        args: ["scan", "pre-commit"]